name: Interview-Scheduler-Db-Backup
on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *"
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@master
      - name: Download file via SSH
        uses: nicklasfrahm/scp-action@main
        with:
          direction: download
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PROD_KEY }}
          port: ${{ secrets.port }}
          insecure_ignore_fingerprint: true
          source: "/home/ubuntu/qxf2/interview-scheduler/data/interviewscheduler.db"
          target: "interviewscheduler.db"
      - name: move the db to new directory
        run: |
          mkdir backup
          ls -al
          mv interviewscheduler.db backup
      - name: Connect s3 bucket
        uses: jakejarvis/s3-sync-action@master
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-east-2'   # optional: defaults to us-east-1
          SOURCE_DIR: '/home/runner/work/interview-scheduler/interview-scheduler/backup'

