name: Interview-Scheduler-Db-Backup
on:
  push:
  pull_request:
  schedule:
    - cron: "* * * * *"
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@master
      - name: Download file via SSH
        uses: nicklasfrahm/scp-action@main
        with:
          direction: download
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PROD_KEY }}
          port: ${{ secrets.port }}
          insecure_ignore_fingerprint: true
          source: "/home/ubuntu/qxf2/interview-scheduler/data/interviewscheduler.db"
          target: "interviewscheduler.db"
      - name: list the tmp directory
        run: |
          pwd
          ls -al
