name: Interview-Scheduler-Db-Backup
on:
  push:
  pull_request:
  schedule:
    - cron: "* * * * *"
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run a multi-line script
      run: |
        mkdir ../tmp
        cp -TR /home/ubuntu/qxf2/interview-scheduler/data/interviewscheduler.db ../tmp
        tar -cvf deploy.tar ../tmp

    - name: Copy file from server to ec2 instance
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PROD_KEY }}
        port: ${{ secrets.port }}
        source: "deploy.tar"
        target: "tmp"


