name: Interview-Scheduler
on:
  push:
    branches:
      - moving_test_to_qa
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: CI-tests
      uses: actions/setup-python@v1
      with:
          python-version: 3.8

    - name: Running the requirements
      with:
        host: ${{ secrets.HOST }}
        MAIL_USER : ${{ secrets.MAIL_USERNAME }}
        MAIL_PASS : ${{ secrets.MAIL_PASSWORD }}
      run: |
        echo $host
        echo $MAIL_USER
        pwd
