name: Interview-Scheduler
on:
  push:
    branches:
      - moving_test_to_qa
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: CI-tests
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Run test
      env:
          MAIL_USERNAME : ${{ secrets.MAIL_USERNAME }}
          MAIL_PASSWORD : ${{ secrets.MAIL_PASSWORD }}
          echo ${{ secrets.MAIL_USERNAME }}
        run: |
             pip install bs4
             cd QA/
             pip install -r requirements.txt
             cd ..
             cat >> qxf2_scheduler/email_config.py <<EOL
             env.MAIL_USERNAME
             env.MAIL_PASSWORD
             EOL
             pwd

      - name: Start run.py in background
        run: |
             pwd
             python run.py
             background: true

      - name: Start run.py in background
        run: |
             pytest QA/tests/test_select_interviewer.py
