name: Interview-Scheduler
on:
  push:
    branches:
      - moving_test_to_qa
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: CI-tests
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - name: Install dependencies
        run: |
          pwd
          cd ..
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run test
        run: pytest QA/tests/test_select_interviewer.py
