name: Interview-Scheduler
on:
  push:
    branches:
      - moving_test_to_qa
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Running the requirements
      uses: actions/setup-python@v1
      with:
          python-version: 3.8
          host: ${{ secrets.HOST }}
          MAIL_USER : ${{ secrets.MAIL_USERNAME }}
          MAIL_PASS : ${{ secrets.MAIL_PASSWORD }}
          script:  |
            echo $host
            echo $MAIL_USER
            cat >> qxf2_scheduler/email_config.py
               MAIL_USERNAME = "$MAIL_USER"
               MAIL_PASSWORD = "$MAIL_PASS"
            SScat qxf2_scheduler/email_config.py
