name: Interview-Scheduler
on:
  push:
    branches:
      - moving_test_to_qa
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Running the requirements
      uses: actions/setup-python@v1
      with:
          python-version: 3.8
    - name: Configure Email Config
      uses: actions/checkout@v2
      with:
          host: ${{ secrets.HOST }}
          MAIL_USER : ${{ secrets.MAIL_USERNAME }}
          MAIL_PASS : ${{ secrets.MAIL_PASSWORD }}
          echo $host
          echo $MAIL_USER