name: Interview-Scheduler
on:
  push:
    branches:
      - moving_test_to_qa
jobs:
  test:
    name: Print mail username
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Running requirements and server in background
        run: |
              pip install -r QA/requirements.txt
              pip install bs4
              touch qxf2_scheduler/email_config.py
              cat > qxf2_scheduler/email_config.py << EOF
              MAIL_USERNAME = "${{ secrets.MAIL_USERNAME }}"
              MAIL_PASSWORD = "${{ secrets.MAIL_PASSWORD }}"
              EOF
              more qxf2_scheduler/email_config.py
              python  run_server.py > /dev/null 2>&1 &
              python -m pytest QA/tests/test_select_interviewer.py
              pkill -f run_server.py
