name: Interview-Scheduler
on:
  push:
    branches:
      - moving_test_to_qa
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: CI-tests
      uses: actions/setup-python@v1
      with:
          python-version: 3.8

    - name: Running the requirements
      uses: actions/checkout@v1
      with:
        host: ${{ secrets.HOST }}
        MAIL_USER : ${{ secrets.MAIL_USERNAME }}
        MAIL_PASS : ${{ secrets.MAIL_PASSWORD }}

    - name: Run server in Background
      run: |
        pwd
        cd QA/
        pip install -r requirements.txt
        cd ..
        pwd
        pip install bs4
        python run.py
        background: true
