name: Interview-Scheduler
on:
  push:
    branches:
      - moving_test_to_qa
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: CI-tests
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Run test
        uses: actions/checkout@v2
        env:
          MAIL_USERNAME : ${{ secrets.MAIL_USERNAME }}
          MAIL_PASSWORD : ${{ secrets.MAIL_PASSWORD }}
      - name: Print
        run: |
          echo "I am print"
          echo $env.MAIL_USERNAME
          cat >> qxf2_scheduler/email_config.py <<EOL
             ${MAIL_USERNAME}
             ${MAIL_PASSWORD}
             EOL

      - name: Start server in background
        run: |
             pip install bs4
             cd QA/
             pip install -r requirements.txt
             cd ..
             pwd
             python run.py
             background: true
