name: Interview-Scheduler
on:
  push:
    branches:
      - moving_test_to_qa
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: CI-tests
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Run test
        uses: actions/checkout@v2
        with:
          host: ${{ secrets.HOST }}
          echo $host
          MAIL_USER : ${{ secrets.MAIL_USERNAME }}
          echo $MAIL_USER
          MAIL_PASS : ${{ secrets.MAIL_PASSWORD }}
      - name: Print
        run: |
          echo $host
          cat >> qxf2_scheduler/email_config.py
             MAIL_USERNAME = "$MAIL_USER"
             MAIL_PASSWORD = "$MAIL_PASS"
          cat qxf2_scheduler/email_config.py
      - name: Start server in background
        run: |
             pip install bs4
             cd QA/
             pip install -r requirements.txt
             cd ..
             pwd
             python run.py
             background: true