name: Interview-Scheduler
on:
  push:
    branches:
      - moving_test_to_qa
jobs:
  test:
    name: Run CI tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Running requirements and server in background
        run: |
              pip install -r QA/requirements.txt
              pip install bs4
              touch qxf2_scheduler/email_config.py
              cat > qxf2_scheduler/email_config.py << EOF
              MAIL_USERNAME = "${{ secrets.MAIL_USERNAME }}"
              MAIL_PASSWORD = "${{ secrets.MAIL_PASSWORD }}"
              EOF
              more qxf2_scheduler/email_config.py
              mkdir data
              python migrate_db.py db migrate
              python migrate_db.py db upgrade
              python qxf2_scheduler/setup_db.py
              pwd
              touch data/candidatestatus.csv
              cat > data/candidatestatus.csv <<EOF
              status_id,status_name
              1,Waiting on Qxf2
              2,Waiting on Candidate
              3,Interview Scheduled
              4,No response
              5,Reject
              6,Hired
              7,Waiting for new opening
              EOF
              more data/candidatestatus.csv
              pwd
              ls -la
              cd /data
              ls -la
              python  run.py > /dev/null 2>&1 &
              python -m pytest QA/tests/test_select_interviewer.py QA/tests/
              test_isapp_api.py
              cat data/candidatestatus.csv
              pkill -f run.py
