name: Interview-Scheduler
on:
  push:
    branches:
      - moving_test_to_qa
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: CI-tests
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Run test
        run: |
             pip install bs4
             cd QA/
             pip install -r requirements.txt
             pwd
             python run.py > /dev/null 2>&1 &
             pytest QA/tests/test_isapp_api.py
