name: Interview-Scheduler
on:
  push:
    branches:
      - moving_test_to_qa
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: CI-tests
        uses: appleboy/ssh-action@master
          script:
           pwd
           pip install virtualenv
           virtualenv -p /usr/bin/python3 qxf2_virtenv
           . qxf2_virtenv/bin/activate
           pip install -r requirements.txt
           cd qxf2/interview-scheduler/QA
           pytest tests/test_select_interviewer.py
           deactivate
