name: Interview-Scheduler
on:
  push:
    branches:
      - moving_test_to_qa
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Running the requirements
      uses: actions/setup-python@v2
      with:
          python-version: 3.8
    - name: Configure Email Config
      with:
          host: ${{ secrets.HOST }}
          MAIL_USERNAME : ${{ secrets.MAIL_USERNAME }}
          MAIL_PASSWORD : ${{ secrets.MAIL_PASSWORD }}
    - name: Print
      run: |
           echo $host
           cat >> qxf2_scheduler/email_config.py
              MAIL_USERNAME = "$MAIL_USER"
              MAIL_PASSWORD = "$MAIL_PASS"
           cat qxf2_scheduler/email_config.py
    - name: Start server in background
      run: |
            pip install bs4
            cd QA/
            pip install -r requirements.txt
            cd ..
            pwd
            python run.py
            background: true