name: Interview-Scheduler
on:
  push:
    branches:
      - moving_test_to_qa
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Running the requirements
      uses: actions/checkout@v2
      with:
        host: ${{ secrets.HOST }}
        MAIL_USER : ${{ secrets.MAIL_USERNAME }}
        MAIL_PASS : ${{ secrets.MAIL_PASSWORD }}
        script:  |
          echo $host
          echo $MAIL_USER
          cat >> qxf2_scheduler/email_config.py
             MAIL_USERNAME = "$MAIL_USER"
             MAIL_PASSWORD = "$MAIL_PASS"
          cat qxf2_scheduler/email_config.py
