name: Interview-Scheduler
on:
  push:
    branches:
      - moving_test_to_qa
jobs:
  test:
    name: Print mail username
    runs-on: ubuntu-latest
    steps:
      - name: Print mail username
        run: |
        if [ "${{ secrets.MAIL_USERNAME }}" == "careers@qxf2.com" ];
        then
            echo "Yay!"
        fi
