name: Interview-Scheduler
on:
  push:
    branches:
      - moving_test_to_qa
jobs:
  test:
    name: Print mail username
    runs-on: ubuntu-latest
    steps:
      - name: Print mail username
        run: |
              if [ "${{ secrets.MAIL_USERNAME }}" == "careers@qxf2.com" ]; then
                echo "Yay!"
              fi
              cd ..
              pwd
              ls -al
              pip install -r QA/requirements.txt
              pip install bs4
              touch qxf2_scheduler/email_config.py
              cat >> qxf2_scheduler/email_config.py
              MAIL_USERNAME = "${{ secrets.MAIL_USERNAME }}"
              MAIL_PASSWORD = "${{ secrets.MAIL_PASSWORD }}"
              more qxf2_scheduler/email_config.py
              python run.py
              background: true
