name: Interview-Scheduler
on:
  push:
    branches:
      - moving_test_to_qa
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Running the requirements
      uses: actions/checkout@v1
      with:
          pwd
