name: Staging-Interview-Scheduler
on:
  push:
    branches:
      - 'staging-new'
jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
    - name: SSH to EC2 instance
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.STAGING_HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.STAGING_PROD_KEY }}
        port: ${{ secrets.port }}
        script:  |
          cd qxf2/interview-scheduler
          source venv-interview-scheduler/bin/activate
          git pull origin master
          pip install -r requirements.txt
          python migrate_db.py db migrate
          python migrate_db.py db upgrade
          sudo service gunicorn restart
          deactivate